"""Add is_bot field to User model

Revision ID: 535750be46f0
Revises: cc028b0c11bc
Create Date: 2025-07-04 11:35:57.454195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535750be46f0'
down_revision = 'cc028b0c11bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bot', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_bot')

    # ### end Alembic commands ###
