"""Add AIPrediction model

Revision ID: 7f5acbcf629a
Revises: 535750be46f0
Create Date: 2025-07-04 13:26:46.342952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5acbcf629a'
down_revision = '535750be46f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_win_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('away_win_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('predicted_winner', sa.String(length=100), nullable=False),
    sa.Column('model_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('betting_recommendation', sa.String(length=100), nullable=False),
    sa.Column('recommended_team', sa.String(length=100), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('kelly_criterion_stake', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_predictions_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_predictions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_predictions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_predictions_match_id'))

    op.drop_table('ai_predictions')
    # ### end Alembic commands ###
