"""trying migraiton

Revision ID: a44beb8837cf
Revises: 
Create Date: 2025-04-18 17:32:15.860235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44beb8837cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('round_id'),
    sa.UniqueConstraint('round_number', 'year', name='uq_round_number_year')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('bankroll', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('external_match_id', sa.String(length=100), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_odds', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('away_odds', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_home_score', sa.Integer(), nullable=True),
    sa.Column('result_away_score', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=100), nullable=True),
    sa.Column('last_odds_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.round_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_external_match_id'), ['external_match_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_matches_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_start_time'))
        batch_op.drop_index(batch_op.f('ix_matches_round_id'))
        batch_op.drop_index(batch_op.f('ix_matches_external_match_id'))

    op.drop_table('matches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_status'))

    op.drop_table('rounds')
    # ### end Alembic commands ###
