"""Add Bet and BankrollHistory models

Revision ID: cc028b0c11bc
Revises: a44beb8837cf
Create Date: 2025-04-30 01:35:27.328048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc028b0c11bc'
down_revision = 'a44beb8837cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('team_selected', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('odds_at_placement', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('potential_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('placement_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.round_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bet_id')
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bets_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_user_id'), ['user_id'], unique=False)

    op.create_table('bankroll_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('related_bet_id', sa.Integer(), nullable=True),
    sa.Column('amount_change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_bet_id'], ['bets.bet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('bankroll_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bankroll_history_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bankroll_history_related_bet_id'), ['related_bet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bankroll_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_bankroll_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankroll_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bankroll_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_bankroll_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_bankroll_history_related_bet_id'))
        batch_op.drop_index(batch_op.f('ix_bankroll_history_change_type'))

    op.drop_table('bankroll_history')
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bets_user_id'))
        batch_op.drop_index(batch_op.f('ix_bets_status'))
        batch_op.drop_index(batch_op.f('ix_bets_round_id'))
        batch_op.drop_index(batch_op.f('ix_bets_match_id'))

    op.drop_table('bets')
    # ### end Alembic commands ###
