"""Add venue and venue_city fields to Match model

Revision ID: d5c85cb78fb8
Revises: 7f5acbcf629a
Create Date: 2025-07-04 13:56:46.692583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c85cb78fb8'
down_revision = '7f5acbcf629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('venue_city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('venue_city')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
